video :
  path : ./video/
logging:
  charset: UTF-8

server:
  port: 8443 #SSL 사용할 포트 지정
  ssl:
    enabled: true
    key-store: ./ssl/abcd.jks
    key-store-type: JKS
    key-store-password: xxxxxxxx  # jks 또는 pfx 암호
    #key-alias: xxxxx.com # (필요시) Alias 명 지정. CSR 자동 생성시에는 CN 명
    #trust-store: # (필요시) "sslcert.co.kr.jks" 또는 "sslcert.co.kr.pfx" 지정. CSR 직접 생성시에는, 루트/체인 스토어 파일 지정
    #trust-store-password: xxxxxxxx  # (필요시) jks 또는 pfx 암호

